;;; Automatically generated by ‘recentf’ on Fri Sep 25 12:45:32 2020.

(setq recentf-list
      '(
        "/Users/dbaggero/go/src/main.go"
        "/Users/dbaggero/.emacs.d/config.org"
        "/Users/dbaggero/.emacs.d_non_lsp/config.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
